name: KAIRO CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-test:
    name: Flutter Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./kairo_mobile
        run: flutter pub get

      - name: Analyze Code
        working-directory: ./kairo_mobile
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run Tests
        working-directory: ./kairo_mobile
        run: flutter test

  functions-deploy:
    name: Deploy Firebase Functions
    needs: flutter-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./functions
        run: npm ci

      - name: Create environment variables
        working-directory: ./functions
        run: echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
